import "@/styles/globals.css";


export default function RootLayout({
    children,
}: Readonly <{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <head>

            </head>
            <body className="bg-white">
                {/* <Container>
                    <Row>
                        <Col> */}
                            {children}
                        {/* </Col>
                    </Row>
                </Container> */}
            </body>
        </html>
    );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         style={{backgroundColor: 'white', color: 'black'}}
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


