import '@/styles/tailwind.css';
import '@/app/globals.css';
import { raleway, inter } from '@/lib/fonts';

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { ThemeProvider } from '@/context/ThemeContext';

import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

export const revlidate = 0;

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale} className={`${raleway.variable} ${inter.variable}`}>
      <body className="flex min-h-screen flex-col">
        <ThemeProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

// <html lang={locale}>
// <head></head>
// <body className={`${roboto.className} flex min-h-screen flex-col`}>
//   <Header />
//   <main className={`container mx-auto flex-grow p-4`}>{children}</main>
//   {/* <Footer /> */}
//   <footer className="bg-gray-800 mt-4 p-4 text-center text-white">
//     <p>&copy; 2025 STW. Все права защищены.</p>
//   </footer>
// </body>
// </html>

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         style={{backgroundColor: 'white', color: 'black'}}
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
