import { Link } from "@/i18n/routing";
import "@/styles/globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
// import Footer from "@/ui/landmarks/footer";
import Header from "@/ui/landmarks/header";
import { Roboto } from "next/font/google";
import { use } from "react"

const roboto = Roboto({
    weight: ['100', '300', '400', '500', '700', '900'],
    subsets: ['latin', 'cyrillic']
});

const bodyClassName = `${roboto.className} bg-white`;

export default async function RootLayout({
    children,
    params
}: Readonly<{
    children: React.ReactNode,
    params: Promise<{ locale: string }>,
}>) {
    const { locale } = await params;
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <head>

            </head>
            <body className={bodyClassName}>
                <NextIntlClientProvider messages={messages}>
                {/* <header>
                    <nav>
                        <ul>
                            <li>Главная</li>
                            <li>О нас</li>
                            <li>Контакты</li>
                            <li>
                                <Link
                                    href={'/product'}>
                                    Продукты
                                </Link>
                            </li>
                        </ul>
                    </nav>
                </header> */}
                <Header />
                <main>
                    {children}
                </main>
                {/* <Footer /> */}
                <footer>
                    <p>&copy; 2025 STW. Все права защищены.</p>
                    <nav>
                        <li>Политика конфиденциальности</li>
                        <li>Условия использования</li>
                    </nav>
                </footer>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         style={{backgroundColor: 'white', color: 'black'}}
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


