import "@/styles/tailwind.css";
import "@/app/globals.css";
import { roboto } from "@/lib/fonts/roboto";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Header from "@/components/layout/Header";


export default async function RootLayout({
    children,
    params
}: Readonly<{
    children: React.ReactNode,
    params: Promise<{ locale: string }>,
}>) {
    const { locale } = await params;
    const messages = await getMessages();

    return (
        <NextIntlClientProvider messages={messages}>
            <html lang={locale}>
                <head>

                </head>
                <body className={`${roboto.className} flex flex-col min-h-screen`}>
                    <Header />
                    <main className={`flex-grow container mx-auto p-4`}>
                        {children}
                    </main>
                    {/* <Footer /> */}
                    <footer className="bg-gray-800 text-white text-center p-4 mt-4">
                        <p>&copy; 2025 STW. Все права защищены.</p>
                    </footer>
                </body>
            </html>
        </NextIntlClientProvider >
    );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         style={{backgroundColor: 'white', color: 'black'}}
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


